---
- include: deploy_monitors.yml
  when: not ceph_containerized_deployment

- include: start_monitor.yml
  when: not ceph_containerized_deployment

- include: ceph_keys.yml
  when: not ceph_containerized_deployment

- include: create_mds_filesystems.yml
  when: not ceph_containerized_deployment and not {{ ceph_version.stdout | version_compare('0.84', '<') }} and mds

- include: docker.yml
  when: ceph_containerized_deployment
